import type { Metadata } from 'next';
import Link from 'next/link';
import LegalChrome from '../_legal/LegalChrome';

// NOTE: Verbatim from the attorney-approved TributeWords Terms (same LLC, same
// Paddle MoR, same AI disclosure), generalized to the Words That Matter service.
// DEC-P-007: do not modify legal content. The collaborative-collection data
// model (contributor memories stored in Postgres until finalize/purge) is NOT
// yet covered by attorney review — see venture-ops open-questions (collection
// privacy addendum) before public launch.

export const metadata: Metadata = { title: 'Terms of Service — Words That Matter' };

export default function TermsPage() {
  return (
    <LegalChrome title="Terms of Service" updated="April 22, 2026">
      <Section n="1. Acceptance of Terms">
        By accessing or using the Words That Matter website and services (collectively, the “Service”), you
        acknowledge that you have read, understood, and agree to be bound by these Terms of Service (“Terms”)
        and our Privacy Policy, which is incorporated herein by reference. If you do not agree to these Terms,
        you may not access or use the Service.
      </Section>
      <Section n="2. Service Description">
        Words That Matter LLC, a Delaware limited liability company effective as of April 21, 2026 (“we”, “us”,
        “our”), provides AI-assisted tribute content generation services. An organizer creates a collection and
        invites others to contribute memories about a person or occasion; we then generate a personalized
        tribute draft using the information provided. The Service is intended to provide creative drafting
        assistance only. It does not provide legal, professional, psychological, or personal advice.
      </Section>
      <Section n="3. Payment and Fees">
        Access to the generated tribute requires a one-time payment. There are no subscriptions or recurring
        charges. All payments are processed securely by Paddle, our authorized merchant of record. By completing
        a purchase, you agree to Paddle’s Buyer Terms and Conditions in addition to these Terms. Paddle controls
        all billing and refund processing.
      </Section>
      <Section n="4. AI-Generated Content and Disclosure">
        <p>
          All content is generated by artificial intelligence based on the information you and your contributors
          provide. The output is a draft intended to serve as a strong starting point. We strongly recommend
          reviewing and personalizing the content before delivery.
        </p>
        <p style={{ marginTop: '1rem', fontWeight: 600 }}>AI Transparency Disclosure.</p>
        <p style={{ marginTop: '0.5rem' }}>
          You acknowledge and agree that all content provided by Words That Matter is generated using artificial
          intelligence technology, specifically large language models (Claude by Anthropic). You are not
          interacting with a human writer. By using the Service, you consent to the use of AI to process your
          inputs and generate the resulting content.
        </p>
        <p style={{ marginTop: '1rem', fontWeight: 600, textTransform: 'uppercase', fontSize: '0.85rem' }}>
          THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” WORDS THAT MATTER MAKES NO REPRESENTATIONS OR
          WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE ACCURACY, COMPLETENESS, APPROPRIATENESS, OR
          FITNESS FOR A PARTICULAR PURPOSE OF ANY GENERATED CONTENT. YOU ARE SOLELY RESPONSIBLE FOR REVIEWING
          THE CONTENT BEFORE USE.
        </p>
      </Section>
      <Section n="5. Contributions and Your Information">
        You and your contributors provide names, memories, and related details used to generate the tribute. You
        represent and warrant that you have the right to invite contributors and that contributions submitted
        through the Service do not violate the privacy or intellectual property rights of any third party. See
        our Privacy Policy for how this information is handled.
      </Section>
      <Section n="6. Acceptable Use">
        <p>You agree not to use the Service to generate or collect content that is:</p>
        <ul style={{ marginTop: '0.5rem', paddingLeft: '1.5rem', listStyle: 'disc' }}>
          <li>Defamatory, harassing, threatening, or harmful to any individual or group;</li>
          <li>Intended for commercial resale or redistribution without our express written permission; or</li>
          <li>In violation of any applicable law or regulation.</li>
        </ul>
        <p style={{ marginTop: '1rem' }}>
          We reserve the right to refuse service, cancel a transaction, or terminate access if we determine, in
          our sole discretion, that your use violates these Terms.
        </p>
      </Section>
      <Section n="7. Intellectual Property Rights">
        Upon payment, you receive a non-exclusive, perpetual license to use, edit, and deliver the generated
        content for personal, non-commercial purposes. You may not resell, sublicense, or redistribute generated
        content as a commercial service. Under current U.S. copyright law, content generated wholly by artificial
        intelligence without sufficient human creative input may not be eligible for copyright protection.
      </Section>
      <Section n="8. Third-Party Services">
        The Service relies on third-party providers, including Paddle for payment processing, Anthropic for AI
        generation, Neon for managed database storage, Resend for email, and Vercel for hosting. We are not
        responsible for the acts, omissions, errors, or service interruptions of any third-party providers.
      </Section>
      <Section n="9. Indemnification">
        You agree to indemnify, defend, and hold harmless Words That Matter LLC, its affiliates, officers,
        directors, employees, and agents from and against any and all claims, liabilities, damages, losses,
        costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to your use
        of the Service, your violation of these Terms, any content you submit, or your violation of any rights
        of a third party.
      </Section>
      <Section n="10. Limitation of Liability">
        <p style={{ fontWeight: 600, textTransform: 'uppercase', fontSize: '0.85rem' }}>
          TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WORDS THAT MATTER LLC SHALL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. IN NO EVENT SHALL OUR TOTAL
          CUMULATIVE LIABILITY EXCEED THE TOTAL AMOUNT YOU PAID FOR THE SERVICE GIVING RISE TO THE CLAIM.
        </p>
      </Section>
      <Section n="11. Governing Law and Dispute Resolution">
        <p>
          These Terms are governed by the laws of the State of Delaware, without regard to its conflict of law
          provisions. Any dispute shall be resolved by binding arbitration administered by JAMS under its
          Streamlined Arbitration Rules, before a single arbitrator, in Wilmington, Delaware.
        </p>
        <p style={{ marginTop: '1rem', fontWeight: 600, textTransform: 'uppercase', fontSize: '0.85rem' }}>
          YOU AND WORDS THAT MATTER LLC AGREE THAT ANY DISPUTE WILL BE BROUGHT SOLELY IN YOUR INDIVIDUAL
          CAPACITY AND NOT AS PART OF A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION.
        </p>
      </Section>
      <Section n="12. Changes to These Terms">
        We reserve the right to modify these Terms at any time. If a revision is material, we will provide at
        least thirty (30) days’ notice. Continued use after revised Terms become effective constitutes acceptance.
      </Section>
      <Section n="13. Contact">
        Questions about these Terms? Contact us at{' '}
        <a href="mailto:hello@wordsbywtm.com" style={{ color: 'var(--primary)' }}>hello@wordsbywtm.com</a>.
      </Section>
      <p style={{ marginTop: '2rem' }}>
        <Link href="/" style={{ color: 'var(--primary)' }}>← Back to start</Link>
      </p>
    </LegalChrome>
  );
}

function Section({ n, children }: { n: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '1.75rem' }}>
      <h2 className="font-serif" style={{ fontSize: '1.35rem', marginBottom: '0.6rem', color: 'var(--foreground)' }}>{n}</h2>
      <div style={{ color: 'var(--muted-foreground)', lineHeight: 1.65 }}>{children}</div>
    </section>
  );
}
